'use client'
import './globals.css'

import Header from "@/components/Header/Header";
import { CartContext } from '@/context/CartContext';
import { useState } from 'react';
import { UserContext } from '@/context/UserContext';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [cartItems,setCartItems] = useState([])
  const [user,setUser] = useState(null);
  const props = {
    cartItems,
    setCartItems
  }
  const userProps = {
    user,
    setUser
  }
  return (
    <html lang="en">
      <title>e-com</title>
      <body className='bg-background text-text' >
        <UserContext.Provider value = {userProps}>
        <CartContext.Provider value={props}>
          <Header />
          {children}
        </CartContext.Provider>
        </UserContext.Provider>
      </body>
    </html>
  )
}
