'use client'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import Header from "@/components/Header/Header";
import { CartContext } from '@/context/CartContext';
import { useState } from 'react';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [cartItems,setCartItems] = useState([])
  const props = {
    cartItems,
    setCartItems
  }
  return (
    <html lang="en">

      <body className='bg-background text-text' >
        <CartContext.Provider value={props}>
          <Header />
          {children}
        </CartContext.Provider>
      </body>
    </html>
  )
}
