'use client'
import './globals.css'

import Header from "@/components/Header/Header";
import { CartContext } from '@/context/CartContext';
import { useState } from 'react';
import { UserProvider } from '@/context/UserContext';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const [cartItems,setCartItems] = useState([])
  const props = {
    cartItems,
    setCartItems
  }
  return (
    <html lang="en">
      <title>e-com</title>
      <body className='bg-background text-text' >
        <UserProvider/>
        <CartContext.Provider value={props}>
          <Header />
          {children}
        </CartContext.Provider>
        <UserProvider/>
      </body>
    </html>
  )
}
